-- App tables. Apply after db/auth.sql (Better Auth, generated by
-- `bunx auth@latest generate --config api/_lib/auth.js --output db/auth.sql`).
--   neon psql < db/auth.sql && neon psql < db/schema.sql
-- Idempotent: safe to re-run.

create table if not exists projects (
  id          text primary key,                 -- 12-char base62, in share URLs (/?p=<id>)
  owner_id    text not null references "user" (id) on delete cascade,
  title       text not null default '',
  data        jsonb not null,                    -- serialize() output; every source url is https
  thumb_url   text,
  visibility  text not null default 'private' check (visibility in ('private', 'unlisted', 'public')),
  hidden      boolean not null default false,    -- moderation: hide from gallery (set by hand)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  deleted_at  timestamptz
);
create index if not exists projects_owner_idx   on projects (owner_id, updated_at desc) where deleted_at is null;
create index if not exists projects_gallery_idx on projects (created_at desc) where deleted_at is null and visibility = 'public' and not hidden;

-- One row per presigned upload: daily quota + the list of a user's B2 objects
-- for any later cleanup sweep.
create table if not exists uploads (
  key         text primary key,                  -- B2 object key u/<userId>/<uuid>.<ext>
  owner_id    text not null references "user" (id) on delete cascade,
  size        bigint not null,
  created_at  timestamptz not null default now()
);
create index if not exists uploads_owner_idx on uploads (owner_id, created_at desc);
